
earliest-cve-date: 2022-07-11
latest-cve-date: 2022-07-13 
run-mode: "download"
stix2-objects-folder: "stix2_objects"
stix2-bundles-folder: "stix2_bundles"
enrichments-folder-path: "stix2_enrichments"