site_name: cve2stix Docs
markdown_extensions:
  - toc:
      permalink: true
theme:
  name: material
  features:
    - navigation.instant
nav:
  - 1. Index: index.md
  - 2. NVD API: nvd-api.md
  - 3. STIX Translations: stix-objects.md
  - 4. Backends: backends.md
docs_dir: docs/
extra:
  generator: false
  version:
    provider: mike
repo_url: https://github.com/signalscorps/cve2stix
repo_name: signalscorps/cve2stix
edit_uri: edit/main/docs/
copyright: Copyright &copy; Signals Corps

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.signalscorps.com/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/signalscorps-public/shared_invite/zt-1exnc12ww-9RKR6aMgO57GmHcl156DAA
    - icon: fontawesome/brands/github
      link: https://github.com/signalscorps