
type: cve
start-date: 2022-10-01
end-date: 2022-10-07
cve-run-mode: "download"
stix2-objects-folder: "stix2_objects"
stix2-bundles-folder: "stix2_bundles"
stix2-enrichments-folder: "stix2_enrichments"