
type: cve
start-date: 2018-04-17
end-date: 2018-04-18
cve-run-mode: "download"
stix2-objects-folder: "stix2_objects"
stix2-bundles-folder: "stix2_bundles"
stix2-enrichments-folder: "stix2_enrichments"
