# Generated by Django 4.1.5 on 2023-01-10 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "cve_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("created", models.DateField()),
                ("modified", models.DateField()),
                ("vulnerability", models.JSONField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
