# Generated by Django 4.1.5 on 2023-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cve2stix_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cve",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="cve",
            name="modified",
            field=models.DateTimeField(),
        ),
    ]
