# Generated by Django 4.1.5 on 2023-01-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cve2stix_api", "0002_alter_cve_created_alter_cve_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cve",
            name="owner",
        ),
    ]
